name: "Custom Issue"
description: "Use this template for custom issues."
labels:
  - custom

body:
  - type: input
    attributes:
      label: "Title"
      description: "Provide a short title for the issue."
      placeholder: "E.g. Feature request or bug."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Description"
      description: "Provide a brief description of the issue."
      placeholder: "Describe the issue in a few sentences."
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: "Prerequisites"
      options:
          - label: "I have read and agree to the [Code of Conduct](https://github.com/CZAsTc/GeoNamesCN/.github/CODE_OF_CONDUCT.md)."
            required: true
          - label: "I have read and agree to the [Contributing Guidelines](https://github.com/CZAsTc/GeoNamesCN/.github/CONTRIBUTING.md)."
            required: true
          - label: "I confirm that this issue has not been mentioned in other [open issues](https://github.com/CZAsTc/GeoNamesCN/issues) or [pull requests](https://github.com/CZAsTc/GeoNamesCN/pulls)."
            required: true
